version: '3.8'
services:
  sso:
    build: .
    env_file:
      - .env
    ports:
      - "${GRPC_PORT}:${GRPC_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - infra-net

networks:
  infra-net:
    external: true