version: '3.8'
services:
  warehouse:
    build: .
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    depends_on:
      postgres:
        condition: service_healthy
      sso:
        condition: service_started
    restart: unless-stopped
    networks:
      - infra-net

networks:
  infra-net:
    external: true